### PR TITLE
Update default polyfill.io version

### PR DESCRIPTION
**Pull request by alexborovkov**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Awesome -- thanks for updating this for me!

Was there a breaking change to the API for `polyfill.io` between versions 2 and 3? Wondering if this would need to be released as a breaking change or not.

**Comment by alexlafroscia** [comment]
Also -- one of the test failures is for running against Node 4 (don't worry about that one) but the other two test cases are the tests actually failing due to the URL changing! Can you fix the tests?

**Comment by wopian** [comment]
Any progress on this @alexlafroscia? Polyfill-io `3.52.1` is the latest version and we're stuck on `2.x.x` with no available documentation (all 3.x now).

All of the failing tests just need the same `v2` -> `v3` replacement.

**Comment by alexlafroscia** [comment]
Nope -- feedback has not been addressed by @AleksandrBorovkov 

If you (@wopian) want to open an alternate PR that includes these commits plus the test changes, I'm happy to review and cut a release with this change!

**Pull request closed without merging**
