### PR TITLE
feat: upgrade to polyfill-io v3

### PR DESCRIPTION
**Pull request by wopian**
Supersedes and closes https://github.com/alexlafroscia/ember-cli-polyfill-io/pull/8

### CODE REVIEW

**Comment by wopian** [comment]
Ember version used in tests fails to install on modern node versions (4.5, 6 or 7 only). Removed the EOL node versions besides `6` and added the active node versions as `allow_failures`, as I'm not in a position to rewrite all the tests from Ember 2.10 (bower) to Ember 3.18.

@alexlafroscia Build status for my fork is here (doesn't seem to be getting new builds here): https://travis-ci.com/github/wopian/ember-cli-polyfill-io/builds/164038128

**Comment by wopian** [comment]
Or rather [Travis' builds aren't being added as status checks](https://github.com/wopian/ember-cli-polyfill-io/commits/v3) to my commits here:

https://travis-ci.org/github/alexlafroscia/ember-cli-polyfill-io/builds/683519888

**Comment by alexlafroscia** [comment]
Thanks for putting this together! I'll get a release out today

**Comment by alexlafroscia** [comment]
`v2.0.0` released, including this update, and a whole lot of other updates/modernizations.

**Pull request merged**
